apiVersion: v1
kind: Secret
metadata:
  name: smishing-backend-secrets
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9Eb21haW46dGVzdEBjbHVzdGVyMC5oNm5ya2w3Lm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
  EMAIL_USER: c3ViaGFzaHNhaW5hbmk0QGdtYWlsLmNvbQ==
  EMAIL_PASS: emZuYiBsa2NsIG9saWQgb2xreQ==
