name: Deploy to Minikube

on:
  push:
    branches:
      - 'BE-docker-kubernetes-feature'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Execution Policy for PowerShell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force

    - name: Display Docker Info
      run: |
        docker info
        docker buildx version
        docker buildx ls

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        driver: "docker-container"
        use: true

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u 2017445 --password-stdin

    - name: Build and tag Docker image
      run: |
        docker build -t 2017445/smishing-backend:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push 2017445/smishing-backend:latest

    - name: Load image into Minikube
      run: |
        minikube image load 2017445/smishing-backend:latest

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/smishing-backend-secrets.yaml

    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/smishing-backend

    - name: Check Minikube Status
      run: |
        minikube status
